package Vista;

import java.io.IOException;
import javax.swing.JButton;

public class VentanaMostrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMostrar.class.getName());
    
    public VentanaMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMostrarCamp = new javax.swing.JButton();
        botonMostrarDonaciones = new javax.swing.JButton();
        botonMostrarInventarioSangre = new javax.swing.JButton();
        botonAtrasMostrar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarCamp.setText("Mostrar campanias");

        botonMostrarDonaciones.setText("Mostrar donaciones");

        botonMostrarInventarioSangre.setText("Mostrar inventario de sangre");

        botonAtrasMostrar.setText("Atras");
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMostrarInventarioSangre)
                    .addComponent(botonMostrarDonaciones)
                    .addComponent(botonMostrarCamp))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtrasMostrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(botonMostrarCamp)
                .addGap(42, 42, 42)
                .addComponent(botonMostrarDonaciones)
                .addGap(50, 50, 50)
                .addComponent(botonMostrarInventarioSangre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(botonAtrasMostrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public JButton getBotonMostrarCamp(){
        return botonMostrarCamp;
    }
    
        public JButton getBotonMostrarDonaciones(){
        return botonMostrarDonaciones;
    }
    
    public JButton getBotonMostrarSangre(){
        return botonMostrarInventarioSangre;
    }
    
    public JButton getBotonAtrasMostrar(){
        return botonAtrasMostrar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasMostrar;
    private javax.swing.JButton botonMostrarCamp;
    private javax.swing.JButton botonMostrarDonaciones;
    private javax.swing.JButton botonMostrarInventarioSangre;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
