package Vista;

import com.mycompany.siacentrosdesangre.Herramientas;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import com.mycompany.siacentrosdesangre.CentroDeSangre;

public class VentanaMostrarCampanias extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMostrarCampanias.class.getName());

    /**
     * Creates new form VentanaMostrarCampanias
     * @throws java.io.IOException
     */
    public VentanaMostrarCampanias(String [][]datos){
        //ArrayList<String> datosArchivo = Herramientas.leerArchivo("datosCampania.txt");//array donde cada posicion e¿son todos los datos juntos de cada campania
        //[[juan*21212*O+], [maria*23131*AB-], ...]
        int x = 0;
        initComponents();
        botonAceptar.setVisible(false);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        
        //por cada posicion del arraylist lo separa y lo pone en otro arreglo 
        //queda [juan, 12121212, O+] y eso se imprime en la primera fila
        while(x < datos.length){
            model.addRow(datos[x]);
            x++;
        }
    }
    
        public VentanaMostrarCampanias(String []datos){
        initComponents();
        botonBuscar.setVisible(false);
        botonAtrasMostrarCamp.setVisible(false);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(datos);
        
    }
    
    public JButton getBotonAtrasMostrarCamp(){
        return botonAtrasMostrarCamp;
    }
    
    public JButton getBotonBuscarCamp(){
        return botonBuscar;
    }
    
    public JButton getBotonAceptar(){
        return botonAceptar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonAtrasMostrarCamp = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ubicacion", "N de Donaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botonAtrasMostrarCamp.setText("Atras");

        botonBuscar.setText("Buscar");

        botonAceptar.setText("Aceptar");
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar)
                .addGap(18, 18, 18)
                .addComponent(botonAtrasMostrarCamp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtrasMostrarCamp)
                    .addComponent(botonBuscar)
                    .addComponent(botonAceptar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAtrasMostrarCamp;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
