package Vista;

import javax.swing.JButton;

public class VentanaModificar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificar.class.getName());

    public VentanaModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonModificarCampania = new javax.swing.JButton();
        botonModificarDonante = new javax.swing.JButton();
        botonModificarFlebotomista = new javax.swing.JButton();
        botonAtrasModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonModificarCampania.setText("Modificar datos de la campaña");

        botonModificarDonante.setText("Modificar datos donante");

        botonModificarFlebotomista.setText("Modificar datos flebotomista");

        botonAtrasModificar.setText("Atrás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonModificarFlebotomista)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonModificarCampania)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botonModificarDonante)
                                    .addGap(23, 23, 23))))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAtrasModificar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(botonModificarCampania)
                .addGap(18, 18, 18)
                .addComponent(botonModificarDonante)
                .addGap(18, 18, 18)
                .addComponent(botonModificarFlebotomista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(botonAtrasModificar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public JButton getBotonModificarCampania(){
        return botonModificarCampania;
    }
    
    public JButton getBotonModificarDonante(){
        return botonModificarDonante;
    }
    
    public JButton getBotonModificarFlebotomista(){
        return botonModificarFlebotomista;
    }
    
    public JButton getBotonAtrasModificar(){
        return botonAtrasModificar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasModificar;
    private javax.swing.JButton botonModificarCampania;
    private javax.swing.JButton botonModificarDonante;
    private javax.swing.JButton botonModificarFlebotomista;
    // End of variables declaration//GEN-END:variables
}
