/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author rafae
 */
public class VentanaEliminar extends javax.swing.JPanel {

    /**
     * Creates new form VentanaEliminar
     */
    public VentanaEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonElimCampania = new javax.swing.JButton();
        botonElimPersona = new javax.swing.JButton();
        botonElimDonacion = new javax.swing.JButton();
        botonElimAtras = new javax.swing.JButton();

        jLabel1.setText("Eliminar");

        botonElimCampania.setText("Eliminar Campania");
        botonElimCampania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElimCampaniaActionPerformed(evt);
            }
        });

        botonElimPersona.setText("Eliminar Persona");

        botonElimDonacion.setText("Eliminar Donacion");

        botonElimAtras.setText("Atrás");
        botonElimAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElimAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonElimCampania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonElimDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonElimPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonElimAtras)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(botonElimCampania)
                .addGap(35, 35, 35)
                .addComponent(botonElimDonacion)
                .addGap(34, 34, 34)
                .addComponent(botonElimPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botonElimAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonElimCampaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElimCampaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonElimCampaniaActionPerformed

    private void botonElimAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElimAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonElimAtrasActionPerformed

    public JButton getBotonElimAtras() {
        return botonElimAtras;
    }

    public JButton getBotonElimCampania() {
        return botonElimCampania;
    }

    public JButton getBotonElimDonacion() {
        return botonElimDonacion;
    }

    public JButton getBotonElimPersona() {
        return botonElimPersona;
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElimAtras;
    private javax.swing.JButton botonElimCampania;
    private javax.swing.JButton botonElimDonacion;
    private javax.swing.JButton botonElimPersona;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
