package Vista;

import javax.swing.JButton;

public class VentanaAgregar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAgregar.class.getName());
    
    public VentanaAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonAgreCampania = new javax.swing.JButton();
        botonAgreDonacion = new javax.swing.JButton();
        botonAgreDonante = new javax.swing.JButton();
        botonAgreAtras = new javax.swing.JButton();
        botonAgreSangre1 = new javax.swing.JButton();
        botonAgreFlebo = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Agregar");

        botonAgreCampania.setText("Agregar Campania");

        botonAgreDonacion.setText("Agregar Donacion");
        botonAgreDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgreDonacionActionPerformed(evt);
            }
        });

        botonAgreDonante.setText("Agregar Donante");
        botonAgreDonante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgreDonanteActionPerformed(evt);
            }
        });

        botonAgreAtras.setText("Atrás");
        botonAgreAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgreAtrasActionPerformed(evt);
            }
        });

        botonAgreSangre1.setText("Agregar Sangre al inventario");
        botonAgreSangre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgreSangre1ActionPerformed(evt);
            }
        });

        botonAgreFlebo.setText("Agregar Flebotomista");
        botonAgreFlebo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgreFleboActionPerformed(evt);
            }
        });
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonAgreCampania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botonAgreDonacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAgreFlebo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAgreDonante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAgreSangre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)
                        .addComponent(botonAgreAtras)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(46, 46, 46)
                .addComponent(botonAgreCampania)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAgreDonacion)
                .addGap(24, 24, 24)
                .addComponent(botonAgreDonante)
                .addGap(18, 18, 18)
                .addComponent(botonAgreFlebo)
                .addGap(18, 18, 18)
                .addComponent(botonAgreSangre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(botonAgreAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgreSangre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgreSangre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgreSangre1ActionPerformed

    private void botonAgreDonanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgreDonanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgreDonanteActionPerformed

    private void botonAgreFleboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgreFleboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgreFleboActionPerformed

    private void botonAgreDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgreDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgreDonacionActionPerformed

    private void botonAgreAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgreAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgreAtrasActionPerformed
    
    public JButton getBotonAgreCampania(){
        return botonAgreCampania;
    }
        
    public JButton getBotonAgreDonacion(){
        return botonAgreDonacion;
    }
        
    public JButton getBotonAgreSangre(){
        return botonAgreDonante;
    }
        
    public JButton getBotonAgreAtras(){
        return botonAgreAtras;
    }
    
    public JButton getBotonAgreDonante(){
        return botonAgreDonante;
    }
    
    public JButton getBotonAgreFlebo(){
        return botonAgreFlebo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgreAtras;
    private javax.swing.JButton botonAgreCampania;
    private javax.swing.JButton botonAgreDonacion;
    private javax.swing.JButton botonAgreDonante;
    private javax.swing.JButton botonAgreFlebo;
    private javax.swing.JButton botonAgreSangre1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
