package Vista;

import java.io.IOException;
import javax.swing.JButton;

public class VentanaMostrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMostrar.class.getName());
    
    public VentanaMostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMostrarCamp = new javax.swing.JButton();
        botonMostrarDonaciones = new javax.swing.JButton();
        botonMostrarInventarioSangre = new javax.swing.JButton();
        botonAtrasMostrar = new javax.swing.JButton();
        botonMostrarPersonasSistema = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMostrarCamp.setText("Mostrar campanias");

        botonMostrarDonaciones.setText("Mostrar donaciones");

        botonMostrarInventarioSangre.setText("Mostrar inventario de sangre");

        botonAtrasMostrar.setText("Atrás");

        botonMostrarPersonasSistema.setText("Mostrar personas registradas");
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAtrasMostrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMostrarDonaciones)
                            .addComponent(botonMostrarCamp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMostrarInventarioSangre)
                    .addComponent(botonMostrarPersonasSistema))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(botonMostrarCamp)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarDonaciones)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarInventarioSangre)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarPersonasSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(botonAtrasMostrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public JButton getBotonMostrarCamp(){
        return botonMostrarCamp;
    }
    
        public JButton getBotonMostrarDonaciones(){
        return botonMostrarDonaciones;
    }
    
    public JButton getBotonMostrarSangre(){
        return botonMostrarInventarioSangre;
    }
    
    public JButton getBotonMostrarPersonas(){
        return botonMostrarPersonasSistema;
    }
    
    public JButton getBotonAtrasMostrar(){
        return botonAtrasMostrar;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtrasMostrar;
    private javax.swing.JButton botonMostrarCamp;
    private javax.swing.JButton botonMostrarDonaciones;
    private javax.swing.JButton botonMostrarInventarioSangre;
    private javax.swing.JButton botonMostrarPersonasSistema;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
